#include "graphics_engine_base_module.ipp"
#include "graphics_engine_device.ipp"
#include "graphics_engine_frame.ipp"
#include "graphics_engine_gui_manager.ipp"
#include "graphics_engine_object.ipp"
#include "graphics_engine_swap_chain.ipp"
#include "graphics_engine_texture.ipp"
#include "graphics_engine_validation_layer.ipp"
#include "graphics_engine_instance.ipp"
#include "graphics_engine_texture_manager.ipp"

#include "game_engine.hpp"